version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: data/web_container/Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - "postgres"
    restart: always
    read_only: true
    cap_drop: [ALL]
    security_opt:
      - no-new-privileges:true
    mem_limit: "512m"
    mem_reservation: "128m"
    cpus: "1.75"
    volumes:
      - ./data/hsm_tokens:/var/lib/softhsm/tokens
    tmpfs:
      - /dev/shm:ro,noexec,nosuid,nodev
    environment:
      - PKCS11_TOKEN=${PKCS11_TOKEN}
      - PKCS11_PIN=${PKCS11_PIN}
      - PKCS11_MODULE=${PKCS11_MODULE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
  postgres:
    # build:
    # context: .
    # dockerfile: data/postgres_container/Dockerfile
    image: postgres:15.0-bullseye@sha256:e21150abf83d89aca1b61c8ccc182cc8164da2571a0d8ee0babce8790bed46ab
    restart: always
    # read_only: true
    # cap_drop: [ALL]
    # security_opt:
    #   - no-new-privileges:true
    mem_limit: "1g"
    mem_reservation: "128m"
    cpus: "1.75"
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
    tmpfs:
      - /dev/shm:ro,noexec,nosuid,nodev
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
